### ISSUE TITLE
InfluxDBStore: incorrect span hierarchy

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/appdash#117]
If my assumptions are correct that both `webapp` and `webapp-influxdb` do the same thing and should generate a basically identical _trace structure_, I think the hierarchy that InfluxDBStore reassembles traces/spans in is incorrect.

**Steps to reproduce:**
- Run `webapp` and visit http://localhost:8699, click on the trace, click on Verbose Data View tab.
- Kill` webapp`, run `webapp-Influxdb`.
- In a new tab, visit http://localhost:8699, click the trace, go to Verbose Data View tab.
- Switch back and forth between the tabs and compare the data displayed.

**What happens?**
- `webapp-influxdb` displays `Client.Foo` fields when viewing the root of the trace (at e.g. http://localhost:8700/traces/419d201ab0ce01d4)

**What should happen?**
- It should in reality only display those `Client.Foo` fields if you have clicked to view a sub-span of the trace, e.g. by clicking `localhost:8699/endpoint (290ms)` / on the `http://localhost:8700/traces/<trace-id>/<sub-span-id>` page.

**Notes:**
- This is not a bug in the web UI / front-end code, but rather it means the frontend is displaying the trace correctly, but it's root vs. sub-span hierarchy is incorrect.

**Comment by chris-ramon** [comment]
Good catch! @slimsag; that's correct `webapp` & `webapp-influxdb` should have identical trace structure.

I've addressed this unexpected behavior on #119.

**Comment by slimsag** [comment]
Fixed by #121
