### ISSUE TITLE
Can use appdash trace golang grpc?

### ISSUE THREAD

**Issue by johnnyluo586** [sourcegraph/appdash#120]
I used grpc in my micro services, can u use appdash trace the grpc request?

**Comment by slimsag** [comment]
Hi @johnnyluo586 -- Appdash can indeed be used to trace the performance and arguments of gRPC services request (both from the client and server perspective). To do this you would simply need to pass a [TimespanEvent](https://godoc.org/sourcegraph.com/sourcegraph/appdash#TimespanEvent) into your recorder via `myRecorder.Event(...)` whenever a gRPC request is made.

Unfortunately, gRPC doesn't allow for easily adding middlewares so you will have to do this manually or via some code generation.

**Comment by slimsag** [comment]
Since this question was answered I'll close this issue :) if you have further questions please feel free to comment or create a new issue.
