### ISSUE TITLE
InfluxDBStore: "retention policy conflicts with an existing policy"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/appdash#133]
Track issue reported by @chris-ramon, with a fix already sent upstream at https://github.com/influxdata/influxdb/pull/6202 -- close once merged.

**Comment by chris-ramon** [comment]
feel free to close this issue @slimsag, since upstream PR [https://github.com/influxdata/influxdb/pull/6202](https://github.com/influxdata/influxdb/pull/6202) was merge.

**Comment by slimsag** [comment]
Very nice, thanks for getting this through!
