### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by adpoint** [sourcegraph/appdash#148]
sourcegraph.com/sourcegraph/appdash/cmd/appdash $ go build
# github.com/influxdata/influxdb/tsdb/engine/tsm1
../../../../../github.com/influxdata/influxdb/tsdb/engine/tsm1/int.go:260: cannot use d.values[:] (type []uint64) as type *[240]uint64 in argument to simple8b.Decode
../../../../../github.com/influxdata/influxdb/tsdb/engine/tsm1/timestamp.go:204: cannot use simple8b.NewDecoder(nil) (type *simple8b.Decoder) as type simple8b.Decoder in field value

**Comment by philips** [comment]
#148 already reported this, you may want to close this out.

**Comment by slimsag** [comment]
Thank you for reporting this, closing in favor of #148
