### ISSUE TITLE
Appdash Tracing in microseconds precision

### ISSUE THREAD

**Issue by ajopanoor** [sourcegraph/appdash#187]
Hi,

I am using Opentracing APIs for Python to send trace data to Appdash collector. The Spans which from my traced events are for "microseconds" granularity. Is there a way in Appdash to plot spans which has durations lesser than milliseconds (say in microseconds)?

Thanks in advance,
Ajo Panoor

**Comment by slimsag** [comment]
Hi @ajopanoor 

Unfortunately it's not possible right now, due to issue https://github.com/sourcegraph/appdash/issues/170 which I haven't had time to fix recently.

I will gladly accept any PR that improves that issue, though :)
