### ISSUE TITLE
Add README and docs

### ISSUE THREAD

**Issue by ernesto-jimenez** [sourcegraph/appdash#2]
Right now there's no details or examples about how apptrace works and ho it is implemented.

It would be good to have some docs so people like me can check how useful the package would be for our use cases and what it would take to integrate it.

**Comment by sqs** [comment]
The README now has a lot more info, and there's a demo app that uses apptrace. Check it out and let me know what you think. We are also hiring a contractor to improve apptrace in a number of ways.

**Comment by slimsag** [comment]
I'm going to close this issue as the README and docs have been improved significantly over the past few months.

If you spot any documentation or other issues/concerns, please feel free to open a new issue specifying what you'd like to see improved.
