### ISSUE TITLE
a Span storage specification issue

### ISSUE THREAD

**Issue by 1046102779** [sourcegraph/appdash#207]
Span type include SpanID and Annotations

I think SpanID is span's own informations, and Annotations data is other infos and these may be empty

but in OpenTracing specfications, span's Operation Name belong itself。so i think Span type's definition is not friendly enough.

but in Appdash , span's OperationName is in Annotations

**Comment by keegancsmith** [comment]
Note that appdash predates OpenTracing. We don't have any current plans on making major changes to the project or the wire format. I assume your issue here is minor and doesn't actually affect functionality? If not please re-open.

**Comment by 1046102779** [comment]
but Appdash use basictracer-go library, the basictracer follows OpenTracing specifications

**Comment by keegancsmith** [comment]
OT support is an extension, not core to appdash. You can log to appdash without using OT.
