### ISSUE TITLE
Adhere to gokit.io tracing spec

### ISSUE THREAD

**Issue by sqs** [sourcegraph/appdash#35]
Depending on how it evolves, it'd be great to adhere to the [gokit tracing spec](https://github.com/peterbourgon/gokit/blob/master/rfc/rfc006-request-tracing.md). Looks like appdash hits all of the points so far except Zipkin compat, which should be doable.

This issue can remain open as a tracking issue.

**Comment by slimsag** [comment]
This will probably come in the form of http://opentracing.io -- though I don't know what the gokit folks think of this, and it's probably too early to bring it up as an issue for them because there aren't many public implementations yet.

**Comment by slimsag** [comment]
I think now that go-kit supports opentracing there is nothing we need to do here. Opentracing is the standard. If anyone disagrees, please open a new issue :)
