### ISSUE TITLE
Degrade gracefully when Flash isn't available.

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/appdash#65]
This is a possible enhancement, non-critical and low priority.

Right now it seems there's no handling of the case when Flash is not available in user's browser (either it's not installed, not available, or disabled).

![image](https://cloud.githubusercontent.com/assets/1924134/7544759/f8c82180-f584-11e4-94ec-1165438b9fc5.png)

Clicking "Copy as JSON" does nothing in such scenario.

If Flash is not available, perhaps something else should happen. Disable copying as json? Display a message saying "Sorry, Flash is needed for this functionality"? Display a text box popup that user can copy/paste? Do something else?

---

As an example of one way to handle such scenario, this is how GitHub looks like when you don't have Flash:

![image](https://cloud.githubusercontent.com/assets/1924134/7544799/4a51bfca-f585-11e4-8f2f-df5f3b51fc5b.png)

And this is how it appears when you do:

![image](https://cloud.githubusercontent.com/assets/1924134/7544805/617dccac-f585-11e4-828f-9c42e66c9056.png)

**Comment by sqs** [comment]
Ooh, just ran into this. It works on Firefox for me but not Chrome, probably because I disabled Flash in Chrome.

It'd be nice if it could just show you the JSON in a textarea (perhaps in a Bootstrap modal). Then you'd be able to copy it no matter what your plugin config was.

**Comment by slimsag** [comment]
I think the best solution would be if Flash isn't available it should just open a popup with a textarea/JSON as @sqs said, it can be pre-selected for you so you can just hit "ctrl+c" (or cmd+c) etc.

**Comment by shurcooL** [comment]
I'm in full agreement with the above proposal.

**Comment by slimsag** [comment]
I just noticed that this is still an issue, #68 fixed it for exporting _single traces_ but not multiple on the `/traces` page:

![image](https://cloud.githubusercontent.com/assets/3173176/7872202/292cbeb4-054b-11e5-8db1-af1819de643f.png)
