### ISSUE TITLE
Documentation: Ruby client

### ISSUE THREAD

**Issue by dim** [sourcegraph/appdash#94]
Hi, not really and issue, but we have created a Ruby client and were wondering if you wanted to mention that in your documentation. Cheers, dim

**Comment by dim** [comment]
https://github.com/bsm/appdash-rb

**Comment by slimsag** [comment]
@dim Amazing! I haven't had a chance to look into it yet and I don't know Ruby, but this is really awesome!

I went ahead and added a new section to the README about language support and linked to your project: https://github.com/sourcegraph/appdash/blob/master/README.md#language-support

Thanks a ton for this and apologies for the late response (somehow I missed the notification)! Cheers
